### ISSUE TITLE
warning: remote HEAD refers to nonexistent ref, unable to checkout.

### ISSUE THREAD

**Issue by swizca** [chimo/gs-reverseFavs#1]
git clone https://github.com/chimo/gs-reverseFavs.git

?

**Comment by chimo** [comment]
Strange... you can clone it from https://code.chromic.org/chimo/gs-reversefavs while I investigate.

**Comment by chimo** [comment]
Okay I think `git clone https://github.com/chimo/gs-reverseFavs.git` should work now.
Let me know!

**Comment by swizca** [comment]
Seems to have gotten it. (I have other issues that prevent me from actually testing - changed to a theme that hides the change theme fields!) Did git clone elsewhere and moved in to where I put the zip contents. That I was able to means you fixed it.

**Comment by chimo** [comment]
(Note to self)

Problem was: https://help.github.com/articles/error-remote-head-refers-to-nonexistent-ref-unable-to-checkout/

Fixed by toggling the default branch back and forth.
