### ISSUE TITLE
Maintaining gs-reverseFavs ...

### ISSUE THREAD

**Issue by swizca** [chimo/gs-reverseFavs#2]
As you're active, and as this is as good a place as any ...

Perhaps you'd answer, and perhaps you'd make a repo wiki article here / out of this, and the answer will be generally net / gnusocial searchable / linked ...

So, having git'ted the plugin, going forwards ...

\# (Debian Jessie, in this case.)
\# Change to gnusocial's plugins directory
cd /var/www/_gnusocial_/plugins
\# Get the plugin.
sudo -u www-data git clone https://github.com/chimo/gs-reverseFavs.git
\# Make gs happy - ln doesn't do it.
sudo -u www-data  mv gs-reverseFavs ReverseFavs
\# Try to keep git happy.
sudo -u www-data  ln -s ReverseFavs gs-reverseFavs
\# Enable plugin
sudo -u www-data  echo "addPlugin('ReverseFavs');" >> ../config.php
\# Keep plugin up to date ...
sudo -u www-data  echo "git \# Some command line here" >> /etc/cron.daily/gsPluginsUpdater.bash
 
Does that all viably hang together?

And the last line should be?

**Comment by chimo** [comment]
I updated the [README](https://github.com/chimo/gs-reverseFavs/blob/gnusocial/README.md) with a couple of things:

1. A better place to put custom plugins is '/local/plugins' (instead of '/plugins').
2. I've added example commands regarding the cloning. You can tell git to use "ReverseFavs" as a folder name instead of the default "gs-reverseFavs" to make GS happy (`git clone https://github.com/chimo/gs-reverseFavs.git ReverseFavs`).

As for the cron job, your script will need to change to the plugin directory and then issue a `git pull` command (with a user that has write permissons to that location, of course).

Let me know if that helps

**Comment by swizca** [comment]
Thanks. Will need to dig into this further, later. Couple thoughts - I have already run into file permission issues, so surrounding things with sudo is probably useful (and/or appropriate chmod / chown commands) [e.g. to a user belonging to the www-data group]; Adding a paragraph about updating / maintaining, would also probably be useful.

Personally, I'm starting to get the feeling I need to / should create a local install / update script. (Shared admin'ing on this machine.) Else others won't be able to easily see what's what - the pointer to local/plugins is REALLY appreciated, thank you! I can put commentary in config.php (as gs guarantees it won't be overwritten) - I'll have to figure out where to put the other files. Perhaps run gnusocial as it's own account and put such in it's home directory.

Thanks for your thoughts, and thanks very much for the quick responses!

**Comment by chimo** [comment]
I added a note about permissions and a "Update" section in the README.

> I guess 'git pull master' is the beastie for a cron job. (Guess one should consider that carefully. If some git repository has added some nastiness, you could pull some unhappiness into your web space.)
> 
> Perhaps more appropriate to set notifications on the repository. Check things out upon such, git pull master, then, manually, if things suit.

Agreed!

**Comment by swizca** [comment]
Nice.

Nicer is that, finally (not 'blaming' you specifically), have a line describing how to know when you've got it 'right'. i.e. 'A Reverse Favs link should appear in the left-nav of your profile page.' (For the longest time I kept wondering if what I was doing in config.php was having any effect - it took a long time to discern that some dashboard config changes don't get reflected back to config.php.)

On the same idea, it's nice that you noted 'you might need to prefix the commands', it would be nicer if you noted what the end permissions should be. Which I'm guessing should be someone (usually www-data), somegroup (usually www-data), and at least 0550/0440 for dirs/files, but could be 0500/0400 depending upon your installation.

'git pull', or 'git pull master'?

It's not clear to me how to be notified of new versions. I see 'Watch', but it seems only to be messaged on all conversations, not just updates.

**Comment by chimo** [comment]
> 'git pull', or 'git pull master'?

If you're tracking `origin/master` (which is usually the default after doing `git clone`), both `git pull` and `git pull master` will do the same thing.

> It's not clear to me how to be notified of new versions. I see 'Watch', but it seems only to be messaged on all conversations, not just updates.

You can change some of the Github notification settings here: https://github.com/settings/notifications

If you use RSS, you can also subscribe to the ['Recent Commits' feed](https://github.com/chimo/gs-reverseFavs/commits/gnusocial.atom) or the ['Releases' feed](https://github.com/chimo/gs-reverseFavs/releases.atom) (note: it seems the 'releases' feed only exists if there's at least 1 release pushed out).

**Comment by swizca** [comment]
Thanks kindly. Lots under the hood of github, much not always particularly apparent. Thanks for the heads up on RSS. Closing.
